_target_: src.models.document_module.DocumentLitModule
_convert_: all

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.dino_vit.DinoVisionTransformerClassifier
  net:
    _target_: torch.hub.load
    repo_or_dir: "facebookresearch/dinov2"
    model: "dinov2_vitb14_reg"
  in_features: 768
  num_classes: 4
  layer_params: [] # pass empty list for a single linear layer

# freeze backbone and make head trainable
freeze_and_trainable: true

# compile model for faster training with pytorch 2.0
compile: false

num_classes: 4
class_to_idx: {}