# @package _global_

defaults:
  - _self_
  - data: document # choose datamodule with `test_dataloader()` for evaluation
  - model: document
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict" # [predict, eval]

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/train/runs/2023-11-14_06-29-44/checkpoints/last.ckpt
