# @package _global_

defaults:
  - _self_
  - data: document # choose datamodule with `test_dataloader()` for evaluation
  - model: document
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict" # predict or eval

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/logs/last.ckpt
